using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyCompanyAttribute("ThoughtWorks Inc.")]
[assembly: AssemblyProductAttribute("CruiseControl.NET")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2003 - 2019 ThoughtWorks Inc.")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyVersionAttribute("1.8.5.0")]
[assembly: AssemblyFileVersionAttribute("1.8.5.0")]
[assembly: AssemblyInformationalVersionAttribute("Git hash : 431744438cdd3e3f61f4988aa05f6482b898971a")]

